from django.urls import path
from main.views import (
    show_main, 
    show_experience, 
    show_skills, 
    create_experience, 
    edit_experience,
    delete_experience,
    create_skill, 
    edit_skill,
    delete_skill,
    create_education,
    edit_education,
    delete_education,
    show_projects,
    create_project,
    edit_project,
    get_projects_json,
    delete_project,
    login_user,
    logout_user,
    show_dashboard,
    create_tech_stack,
    edit_tech_stack,
    delete_tech_stack,
    get_experience_json,
    get_skills_json,
    get_education_json,
    get_tech_stack_json,
)

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('experience/', show_experience, name='show_experience'),
    path('skills/', show_skills, name='show_skills'),
    path('experience/add/', create_experience, name='create_experience'),
    path('experience/edit/<uuid:id>/', edit_experience, name='edit_experience'),
    path('experience/delete/<uuid:id>/', delete_experience, name='delete_experience'),
    path('skills/add/', create_skill, name='create_skill'),
    path('skills/edit/<uuid:id>/', edit_skill, name='edit_skill'),
    path('skills/delete/<uuid:id>/', delete_skill, name='delete_skill'),
    path('education/add/', create_education, name='create_education'),
    path('education/edit/<int:id>/', edit_education, name='edit_education'),
    path('education/delete/<int:id>/', delete_education, name='delete_education'),
    path('projects/', show_projects, name='show_projects'),
    path('projects/add/', create_project, name='create_project'),
    path('projects/edit/<uuid:id>/', edit_project, name='edit_project'),
    path('api/projects/', get_projects_json, name='get_projects_json'),
    path('api/experience/', get_experience_json, name='get_experience_json'),
    path('api/skills/', get_skills_json, name='get_skills_json'),
    path('api/education/', get_education_json, name='get_education_json'),
    path('api/techstack/', get_tech_stack_json, name='get_tech_stack_json'),
    path("projects/<uuid:project_id>/delete/", delete_project, name="delete_project"),
    path('techstack/add/', create_tech_stack, name='create_tech_stack'),
    path('techstack/edit/<int:id>/', edit_tech_stack, name='edit_tech_stack'),
    path('techstack/delete/<int:id>/', delete_tech_stack, name='delete_tech_stack'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('dashboard/', show_dashboard, name='dashboard'),
]