# Generated by Django 6.1 on 2026-09-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='code_snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
