# Generated by Django 6.1 on 2026-09-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
    ]
