# Generated by Django 6.1 on 2026-09-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_experience_company_alter_experience_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Dev', 'Web Development'), ('Machine Learning', 'Machine Learning'), ('Mobile App', 'Mobile App'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
