# Generated by Django 6.1 on 2026-09-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama bahasa (contoh: Python)', max_length=50)),
                ('icon_url', models.URLField(help_text='URL ikon devicon (SVG/PNG)')),
                ('filename', models.CharField(help_text='Nama file untuk Mac UI (contoh: script.py)', max_length=50)),
                ('code_snippet', models.TextField(help_text='Contoh kode program')),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan di halaman')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
