# Generated by Django 6.1 on 2026-09-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_education_starred_by_experience_starred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Tampilkan di halaman utama sebagai Featured Project'),
        ),
    ]
