# Generated by Django 6.1 on 2026-09-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_project_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='starred_by',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='starred_by',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='starred_by',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='starred_by',
        ),
    ]
